version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_redcap
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pg_redcap
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_redcap
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: aluisr@minsait.com
      PGADMIN_DEFAULT_PASSWORD: rodovalho@21
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  pgdata:
